# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ruta_imagen',
            field=models.FileField(default='defecto/defecto.png', upload_to='fotos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_publicacion',
            field=models.DateField(auto_now=True),
        ),
    ]
