# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ruta_imagen',
            field=models.FileField(blank=True, default='defecto/defecto.png', null=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
